### PR TITLE
Js beginnings

### PR DESCRIPTION
**Pull request by csndra0504**
- add temp html
- setup slider to use config
- add next slide functionality
- add prev slide functionality
- add auto slide functionality

### CODE REVIEW

**Review by nellarro — COMMENTED** [review]
- jQuery was not yet approved in the doc by @MsAleia. 
- Merge into a development branch before merge to master

**Comment by csndra0504** [comment]
@nellarro I've asked Ann to create a develop branch. I don't have those permissions. Fingers crossed that she does! I'll change the base when its available. I'll also refactor out the jQuery and in the ES6. :)

**Comment by csndra0504** [comment]
Thanks for the new branch @redrambles !!! 
bitmoji

**Comment by wking-io** [comment]
What's all this?? Also did I hear ES6? 🙌🙌🙌

**Comment by csndra0504** [comment]
@nellarro @MsAleia I removed jQuery and I used ES6 wherever it seemed to make sense. 

There is some funky looking code (see added lines 61 & 62 from simple-slider.js in my latest commit) related to the fact that `getElementsByClassName` returns a nodelist rather than a true array. Nodelists look like arrays but aren't so they don't come with the array methods we like to use in ES6 (filter, reduce, etc...). To convert them to arrays I used the ES6 spread operator. It works, but its looking a little funky. I don't think I've ever seen code like this in the wild because 1) we usually use jQuery for DOM manipulation and it eases this weirdness, 2) we aren't typically doing DOM manipulation when we use ES6 (because React). Maybe theres a better alternative I'm missing, but right now what I've got is a little cringe-worthy lol :P Bringing jQuery back in might actually make the code simpler. Let me know your thoughts! We can keep it as is if you think its fine. Its kinda fun, just a little weird.

**Comment by wking-io** [comment]
PS - Sorry if my comments in the code started some review thing...😬

**Comment by MsAleia** [comment]
No worries @wking-io ! We're planning for a code-a-long this month! 

Cassie incorporating the jQuery with ES6 is no problem. Are you saying including the ES6 at all is making everything a bit chunky to explain/understand?

**Comment by wking-io** [comment]
That sounds awesome! If there is anything I can help with especially ES6 fun let me know! I will keep up with the repo and try not to get in the way. :)

**Comment by csndra0504** [comment]
Haha @wking-io no you didn't start anything. :) And your feedback is totally welcome! I've never used ES6 in this context so its a learning experience to see how it actually pans out in a practical sense.

@MsAleia The ES6 on its own isn't causing the issue. In this particular case the funkiness is coming from the nodelist which is just a JavaScript thing. jQuery would simplify that and a few other things.

**Review by nellarro — APPROVED** [review]
This can be our look at ES6. jQuery is added. We should probably only be doing two lines of es6 if we do use it. Looking like we'll do jQuery for all.

**Comment by MsAleia** [comment]
@csndra0504 The point of sessions like this is to expose students to something they haven't seen before. And since you're teaching a little ES6 in the presentation - it needs to be there! I think it's pretty [safe to use](http://caniuse.com/#search=es6), just share that it's not currently supported on IE11 but in 6 months when someone comes across this (all about the longevity) it may be supported on IE and they'll be able to use it freely.

**Pull request merged**
